language: node_js
env:
    - GOPATH=$HOME/go PATH=$GOPATH/bin:$PATH
before_script:
    - npm install -g coveralls
    - go get github.com/jpmonette/apexcov

node_js:
    - "7"
install:
    - npm install -g jsforce-metadata-tools
script:
    - jsforce-deploy --dry-run -u $DEPLOYMENT_USERNAME -p $DEPLOYMENT_PASSWORD$DEPLOYMENT_TOKEN -D $TRAVIS_BUILD_DIR/src -l $DEPLOYMENT_LOGIN_URL --rollbackOnError true --testLevel $DEPLOYMENT_TEST_LEVEL --pollTimeout $POLL_TIMEOUT
    - apexcov
    - codeclimate-test-reporter < ./coverage/lcov.info
