language: node_js
env:
    - GOPATH=$HOME/go PATH=$GOPATH/bin:$PATH
before_script:
    - npm install -g coveralls
node_js:
    - "7"
install:
    - npm install -g jsforce-metadata-tools
script:
    - jsforce-deploy $DEPLOYMENT_DRY_RUN -u $DEPLOYMENT_USERNAME -p $DEPLOYMENT_PASSWORD$DEPLOYMENT_TOKEN -D $TRAVIS_BUILD_DIR/src -l $DEPLOYMENT_LOGIN_URL --rollbackOnError true --testLevel $DEPLOYMENT_TEST_LEVEL --pollTimeout $POLL_TIMEOUT --pollInterval $POLL_INTERVAL--verbose